import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Header from "@/components/Header/Header";
import FeatureListing from "@/components/FeatureListing/FeatureListing";
import classNames from "classnames";
import MainBanner from "@/components/MainBanner/MainBanner";
import RechargeTab from "@/components/RechargeTab/RechargeTab";


export default function Home() {
  const router = useRouter();

  // useEffect(() => {
  //   router.push("/");
  // }, []);

 
  return (
    <>
      <Head>
        <title>E-Pay Web App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <MainBanner bgImg={"https://img.freepik.com/premium-vector/3d-isometric-web-banner-wallet-credit-card-connected-transfer-money-smartphone-e-wallet-mobile-payment-landing-page-concept_47328-1249.jpg"} />

      

      <FeatureListing />

     
      <RechargeTab />

      <section className={styles.offer_sec}>
        <div className="container">
          <div className="row">
            <div className="col-12">
              <h1>
                Offers <span>Just the way you like</span>
              </h1>
              <p>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                Aperiam dolore accusantium doloribus dolorum inventore hic quod.
              </p>
            </div>

            <div className="col-md-3 col-12">
              <div className={styles.offer_img}>
                <img src="/images/mobilesite-offer-myrupee.jpg" alt="" />
              </div>
            </div>
            <div className="col-md-3 col-12">
              <div className={styles.offer_img}>
                <img src="/images/mobilesite-offer-recharge (1).jpg" alt="" />
              </div>
            </div>
            <div className="col-md-3 col-12">
              <div className={styles.offer_img}>
                <img src="/images/mobilesite-offer-recharge.jpg" alt="" />
              </div>
            </div>
            <div className="col-md-3 col-12">
              <div className={styles.offer_img}>
                <img src="/images/mobilesite-offer-refer.jpg" alt="" />
              </div>
            </div>
          </div>
        </div>
      </section>

     
    </>
  );
}

//  {/* <div className={styles.recharge_Wrapper}>
//         <div className="container">
//           <div className="row">
//             <div className="col-12">
//               <RechargeSec />
//             </div>
//           </div>
//         </div>
//       </div> */}
// {/* <div className={styles.feature_listing}>
//         <div className="container">
//           <div className="row justify-content-center">
//             <div className="col-12">
//               <h2>Featured Listings</h2>
//             </div>
//             {data.map((item) => {
//               return (
//                 <>
//                   <div className={classNames("col-3 mb-1", styles.col_3)}>
//                     <FeatureListing item={item} />
//                   </div>
//                 </>
//               );
//             })}
//           </div>
//         </div>
//       </div> */}
  // {/* <form action="" >
  //         <input type="text" value={name} onChange={(e)=>setName(e.target.value)} />
  //         <input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} />
  //         <input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} />
  //         <button type="button" onClick={handleSubmit}>send</button>
  //       </form> */}